<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: IPPN.proto

namespace Catalyst\Protocol\IPPN;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>Catalyst.Protocol.IPPN.LatestDeltaHashResponse</code>
 */
class LatestDeltaHashResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>bool isSync = 1;</code>
     */
    private $isSync = false;
    /**
     * <pre>
     * K given del
     * </pre>
     *
     * <code>.Catalyst.Protocol.Deltas.DeltaIndex deltaIndex = 2;</code>
     */
    private $deltaIndex = null;

    public function __construct() {
        \GPBMetadata\IPPN::initOnce();
        parent::__construct();
    }

    /**
     * <code>bool isSync = 1;</code>
     */
    public function getIsSync()
    {
        return $this->isSync;
    }

    /**
     * <code>bool isSync = 1;</code>
     */
    public function setIsSync($var)
    {
        GPBUtil::checkBool($var);
        $this->isSync = $var;
    }

    /**
     * <pre>
     * K given del
     * </pre>
     *
     * <code>.Catalyst.Protocol.Deltas.DeltaIndex deltaIndex = 2;</code>
     */
    public function getDeltaIndex()
    {
        return $this->deltaIndex;
    }

    /**
     * <pre>
     * K given del
     * </pre>
     *
     * <code>.Catalyst.Protocol.Deltas.DeltaIndex deltaIndex = 2;</code>
     */
    public function setDeltaIndex(&$var)
    {
        GPBUtil::checkMessage($var, \Catalyst\Protocol\Deltas\DeltaIndex::class);
        $this->deltaIndex = $var;
    }

}

