// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Network.proto

#include "Network.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace Catalyst {
namespace Protocol {
namespace Network {
}  // namespace Network
}  // namespace Protocol
}  // namespace Catalyst
static constexpr ::PROTOBUF_NAMESPACE_ID::Metadata* file_level_metadata_Network_2eproto = nullptr;
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_Network_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_Network_2eproto = nullptr;
const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_Network_2eproto::offsets[1] = {};
static constexpr ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema* schemas = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_Network_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\rNetwork.proto\022\031Catalyst.Protocol.Netwo"
  "rk*M\n\013NetworkType\022\030\n\024NETWORK_TYPE_UNKNOW"
  "N\020\000\022\013\n\007MAINNET\020\001\022\n\n\006DEVNET\020\002\022\013\n\007TESTNET\020"
  "\003B\002P\001b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_Network_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_Network_2eproto_sccs[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_Network_2eproto_once;
static bool descriptor_table_Network_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Network_2eproto = {
  &descriptor_table_Network_2eproto_initialized, descriptor_table_protodef_Network_2eproto, "Network.proto", 133,
  &descriptor_table_Network_2eproto_once, descriptor_table_Network_2eproto_sccs, descriptor_table_Network_2eproto_deps, 0, 0,
  schemas, file_default_instances, TableStruct_Network_2eproto::offsets,
  file_level_metadata_Network_2eproto, 0, file_level_enum_descriptors_Network_2eproto, file_level_service_descriptors_Network_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_Network_2eproto = (  ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_Network_2eproto), true);
namespace Catalyst {
namespace Protocol {
namespace Network {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* NetworkType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Network_2eproto);
  return file_level_enum_descriptors_Network_2eproto[0];
}
bool NetworkType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace Network
}  // namespace Protocol
}  // namespace Catalyst
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
