<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Rpc.proto

namespace Catalyst\Protocol\Rpc\Node;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>Catalyst.Protocol.Rpc.Node.TransferFileBytesRequest</code>
 */
class TransferFileBytesRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>uint32 chunk_id = 1;</code>
     */
    private $chunk_id = 0;
    /**
     * <code>bytes chunk_bytes = 2;</code>
     */
    private $chunk_bytes = '';
    /**
     * <code>bytes correlation_file_name = 3;</code>
     */
    private $correlation_file_name = '';

    public function __construct() {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct();
    }

    /**
     * <code>uint32 chunk_id = 1;</code>
     */
    public function getChunkId()
    {
        return $this->chunk_id;
    }

    /**
     * <code>uint32 chunk_id = 1;</code>
     */
    public function setChunkId($var)
    {
        GPBUtil::checkUint32($var);
        $this->chunk_id = $var;
    }

    /**
     * <code>bytes chunk_bytes = 2;</code>
     */
    public function getChunkBytes()
    {
        return $this->chunk_bytes;
    }

    /**
     * <code>bytes chunk_bytes = 2;</code>
     */
    public function setChunkBytes($var)
    {
        GPBUtil::checkString($var, False);
        $this->chunk_bytes = $var;
    }

    /**
     * <code>bytes correlation_file_name = 3;</code>
     */
    public function getCorrelationFileName()
    {
        return $this->correlation_file_name;
    }

    /**
     * <code>bytes correlation_file_name = 3;</code>
     */
    public function setCorrelationFileName($var)
    {
        GPBUtil::checkString($var, False);
        $this->correlation_file_name = $var;
    }

}

