<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Rpc.proto

namespace Catalyst\Protocol\Rpc\Node;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Catalyst.Protocol.Rpc.Node.VerifyMessageRequest</code>
 */
class VerifyMessageRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes signature = 1;</code>
     */
    private $signature = '';
    /**
     * Generated from protobuf field <code>bytes public_key = 2;</code>
     */
    private $public_key = '';
    /**
     * Generated from protobuf field <code>bytes message = 3;</code>
     */
    private $message = '';
    /**
     * Generated from protobuf field <code>.Catalyst.Protocol.Cryptography.SigningContext signing_context = 4;</code>
     */
    private $signing_context = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $signature
     *     @type string $public_key
     *     @type string $message
     *     @type \Catalyst\Protocol\Cryptography\SigningContext $signing_context
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes signature = 1;</code>
     * @return string
     */
    public function getSignature()
    {
        return $this->signature;
    }

    /**
     * Generated from protobuf field <code>bytes signature = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSignature($var)
    {
        GPBUtil::checkString($var, False);
        $this->signature = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes public_key = 2;</code>
     * @return string
     */
    public function getPublicKey()
    {
        return $this->public_key;
    }

    /**
     * Generated from protobuf field <code>bytes public_key = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPublicKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->public_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes message = 3;</code>
     * @return string
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * Generated from protobuf field <code>bytes message = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, False);
        $this->message = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Catalyst.Protocol.Cryptography.SigningContext signing_context = 4;</code>
     * @return \Catalyst\Protocol\Cryptography\SigningContext
     */
    public function getSigningContext()
    {
        return $this->signing_context;
    }

    /**
     * Generated from protobuf field <code>.Catalyst.Protocol.Cryptography.SigningContext signing_context = 4;</code>
     * @param \Catalyst\Protocol\Cryptography\SigningContext $var
     * @return $this
     */
    public function setSigningContext($var)
    {
        GPBUtil::checkMessage($var, \Catalyst\Protocol\Cryptography\SigningContext::class);
        $this->signing_context = $var;

        return $this;
    }

}

