// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Rpc.proto

package Catalyst.Protocol.Rpc.Node;

/**
 * Protobuf type {@code Catalyst.Protocol.Rpc.Node.GetDeltaResponse}
 */
public  final class GetDeltaResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Catalyst.Protocol.Rpc.Node.GetDeltaResponse)
    GetDeltaResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetDeltaResponse.newBuilder() to construct.
  private GetDeltaResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetDeltaResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetDeltaResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetDeltaResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            Catalyst.Protocol.Deltas.Delta.Builder subBuilder = null;
            if (delta_ != null) {
              subBuilder = delta_.toBuilder();
            }
            delta_ = input.readMessage(Catalyst.Protocol.Deltas.Delta.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(delta_);
              delta_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Catalyst.Protocol.Rpc.Node.Rpc.internal_static_Catalyst_Protocol_Rpc_Node_GetDeltaResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Catalyst.Protocol.Rpc.Node.Rpc.internal_static_Catalyst_Protocol_Rpc_Node_GetDeltaResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            Catalyst.Protocol.Rpc.Node.GetDeltaResponse.class, Catalyst.Protocol.Rpc.Node.GetDeltaResponse.Builder.class);
  }

  public static final int DELTA_FIELD_NUMBER = 1;
  private Catalyst.Protocol.Deltas.Delta delta_;
  /**
   * <code>.Catalyst.Protocol.Deltas.Delta delta = 1;</code>
   * @return Whether the delta field is set.
   */
  public boolean hasDelta() {
    return delta_ != null;
  }
  /**
   * <code>.Catalyst.Protocol.Deltas.Delta delta = 1;</code>
   * @return The delta.
   */
  public Catalyst.Protocol.Deltas.Delta getDelta() {
    return delta_ == null ? Catalyst.Protocol.Deltas.Delta.getDefaultInstance() : delta_;
  }
  /**
   * <code>.Catalyst.Protocol.Deltas.Delta delta = 1;</code>
   */
  public Catalyst.Protocol.Deltas.DeltaOrBuilder getDeltaOrBuilder() {
    return getDelta();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (delta_ != null) {
      output.writeMessage(1, getDelta());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (delta_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getDelta());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof Catalyst.Protocol.Rpc.Node.GetDeltaResponse)) {
      return super.equals(obj);
    }
    Catalyst.Protocol.Rpc.Node.GetDeltaResponse other = (Catalyst.Protocol.Rpc.Node.GetDeltaResponse) obj;

    if (hasDelta() != other.hasDelta()) return false;
    if (hasDelta()) {
      if (!getDelta()
          .equals(other.getDelta())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasDelta()) {
      hash = (37 * hash) + DELTA_FIELD_NUMBER;
      hash = (53 * hash) + getDelta().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static Catalyst.Protocol.Rpc.Node.GetDeltaResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Catalyst.Protocol.Rpc.Node.GetDeltaResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Catalyst.Protocol.Rpc.Node.GetDeltaResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Catalyst.Protocol.Rpc.Node.GetDeltaResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Catalyst.Protocol.Rpc.Node.GetDeltaResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Catalyst.Protocol.Rpc.Node.GetDeltaResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Catalyst.Protocol.Rpc.Node.GetDeltaResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Catalyst.Protocol.Rpc.Node.GetDeltaResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static Catalyst.Protocol.Rpc.Node.GetDeltaResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static Catalyst.Protocol.Rpc.Node.GetDeltaResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static Catalyst.Protocol.Rpc.Node.GetDeltaResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Catalyst.Protocol.Rpc.Node.GetDeltaResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(Catalyst.Protocol.Rpc.Node.GetDeltaResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Catalyst.Protocol.Rpc.Node.GetDeltaResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Catalyst.Protocol.Rpc.Node.GetDeltaResponse)
      Catalyst.Protocol.Rpc.Node.GetDeltaResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Catalyst.Protocol.Rpc.Node.Rpc.internal_static_Catalyst_Protocol_Rpc_Node_GetDeltaResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Catalyst.Protocol.Rpc.Node.Rpc.internal_static_Catalyst_Protocol_Rpc_Node_GetDeltaResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Catalyst.Protocol.Rpc.Node.GetDeltaResponse.class, Catalyst.Protocol.Rpc.Node.GetDeltaResponse.Builder.class);
    }

    // Construct using Catalyst.Protocol.Rpc.Node.GetDeltaResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (deltaBuilder_ == null) {
        delta_ = null;
      } else {
        delta_ = null;
        deltaBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Catalyst.Protocol.Rpc.Node.Rpc.internal_static_Catalyst_Protocol_Rpc_Node_GetDeltaResponse_descriptor;
    }

    @java.lang.Override
    public Catalyst.Protocol.Rpc.Node.GetDeltaResponse getDefaultInstanceForType() {
      return Catalyst.Protocol.Rpc.Node.GetDeltaResponse.getDefaultInstance();
    }

    @java.lang.Override
    public Catalyst.Protocol.Rpc.Node.GetDeltaResponse build() {
      Catalyst.Protocol.Rpc.Node.GetDeltaResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public Catalyst.Protocol.Rpc.Node.GetDeltaResponse buildPartial() {
      Catalyst.Protocol.Rpc.Node.GetDeltaResponse result = new Catalyst.Protocol.Rpc.Node.GetDeltaResponse(this);
      if (deltaBuilder_ == null) {
        result.delta_ = delta_;
      } else {
        result.delta_ = deltaBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof Catalyst.Protocol.Rpc.Node.GetDeltaResponse) {
        return mergeFrom((Catalyst.Protocol.Rpc.Node.GetDeltaResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(Catalyst.Protocol.Rpc.Node.GetDeltaResponse other) {
      if (other == Catalyst.Protocol.Rpc.Node.GetDeltaResponse.getDefaultInstance()) return this;
      if (other.hasDelta()) {
        mergeDelta(other.getDelta());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Catalyst.Protocol.Rpc.Node.GetDeltaResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (Catalyst.Protocol.Rpc.Node.GetDeltaResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Catalyst.Protocol.Deltas.Delta delta_;
    private com.google.protobuf.SingleFieldBuilderV3<
        Catalyst.Protocol.Deltas.Delta, Catalyst.Protocol.Deltas.Delta.Builder, Catalyst.Protocol.Deltas.DeltaOrBuilder> deltaBuilder_;
    /**
     * <code>.Catalyst.Protocol.Deltas.Delta delta = 1;</code>
     * @return Whether the delta field is set.
     */
    public boolean hasDelta() {
      return deltaBuilder_ != null || delta_ != null;
    }
    /**
     * <code>.Catalyst.Protocol.Deltas.Delta delta = 1;</code>
     * @return The delta.
     */
    public Catalyst.Protocol.Deltas.Delta getDelta() {
      if (deltaBuilder_ == null) {
        return delta_ == null ? Catalyst.Protocol.Deltas.Delta.getDefaultInstance() : delta_;
      } else {
        return deltaBuilder_.getMessage();
      }
    }
    /**
     * <code>.Catalyst.Protocol.Deltas.Delta delta = 1;</code>
     */
    public Builder setDelta(Catalyst.Protocol.Deltas.Delta value) {
      if (deltaBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        delta_ = value;
        onChanged();
      } else {
        deltaBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Catalyst.Protocol.Deltas.Delta delta = 1;</code>
     */
    public Builder setDelta(
        Catalyst.Protocol.Deltas.Delta.Builder builderForValue) {
      if (deltaBuilder_ == null) {
        delta_ = builderForValue.build();
        onChanged();
      } else {
        deltaBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Catalyst.Protocol.Deltas.Delta delta = 1;</code>
     */
    public Builder mergeDelta(Catalyst.Protocol.Deltas.Delta value) {
      if (deltaBuilder_ == null) {
        if (delta_ != null) {
          delta_ =
            Catalyst.Protocol.Deltas.Delta.newBuilder(delta_).mergeFrom(value).buildPartial();
        } else {
          delta_ = value;
        }
        onChanged();
      } else {
        deltaBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Catalyst.Protocol.Deltas.Delta delta = 1;</code>
     */
    public Builder clearDelta() {
      if (deltaBuilder_ == null) {
        delta_ = null;
        onChanged();
      } else {
        delta_ = null;
        deltaBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Catalyst.Protocol.Deltas.Delta delta = 1;</code>
     */
    public Catalyst.Protocol.Deltas.Delta.Builder getDeltaBuilder() {
      
      onChanged();
      return getDeltaFieldBuilder().getBuilder();
    }
    /**
     * <code>.Catalyst.Protocol.Deltas.Delta delta = 1;</code>
     */
    public Catalyst.Protocol.Deltas.DeltaOrBuilder getDeltaOrBuilder() {
      if (deltaBuilder_ != null) {
        return deltaBuilder_.getMessageOrBuilder();
      } else {
        return delta_ == null ?
            Catalyst.Protocol.Deltas.Delta.getDefaultInstance() : delta_;
      }
    }
    /**
     * <code>.Catalyst.Protocol.Deltas.Delta delta = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        Catalyst.Protocol.Deltas.Delta, Catalyst.Protocol.Deltas.Delta.Builder, Catalyst.Protocol.Deltas.DeltaOrBuilder> 
        getDeltaFieldBuilder() {
      if (deltaBuilder_ == null) {
        deltaBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            Catalyst.Protocol.Deltas.Delta, Catalyst.Protocol.Deltas.Delta.Builder, Catalyst.Protocol.Deltas.DeltaOrBuilder>(
                getDelta(),
                getParentForChildren(),
                isClean());
        delta_ = null;
      }
      return deltaBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Catalyst.Protocol.Rpc.Node.GetDeltaResponse)
  }

  // @@protoc_insertion_point(class_scope:Catalyst.Protocol.Rpc.Node.GetDeltaResponse)
  private static final Catalyst.Protocol.Rpc.Node.GetDeltaResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Catalyst.Protocol.Rpc.Node.GetDeltaResponse();
  }

  public static Catalyst.Protocol.Rpc.Node.GetDeltaResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetDeltaResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetDeltaResponse>() {
    @java.lang.Override
    public GetDeltaResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetDeltaResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetDeltaResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetDeltaResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public Catalyst.Protocol.Rpc.Node.GetDeltaResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

