// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Rpc.proto

package Catalyst.Protocol.Rpc.Node;

public interface GetPeerReputationResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Catalyst.Protocol.Rpc.Node.GetPeerReputationResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 reputation = 1;</code>
   * @return The reputation.
   */
  int getReputation();
}
