// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Rpc.proto

package Catalyst.Protocol.Rpc.Node;

public interface SetPeerDataFolderRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Catalyst.Protocol.Rpc.Node.SetPeerDataFolderRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string data_folder = 1;</code>
   */
  java.lang.String getDataFolder();
  /**
   * <code>string data_folder = 1;</code>
   */
  com.google.protobuf.ByteString
      getDataFolderBytes();
}
