// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Rpc.proto

package Catalyst.Protocol.Rpc.Node;

public interface SignMessageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Catalyst.Protocol.Rpc.Node.SignMessageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes message = 1;</code>
   */
  com.google.protobuf.ByteString getMessage();

  /**
   * <code>string key_id = 2;</code>
   */
  java.lang.String getKeyId();
  /**
   * <code>string key_id = 2;</code>
   */
  com.google.protobuf.ByteString
      getKeyIdBytes();

  /**
   * <code>.Catalyst.Protocol.Cryptography.SigningContext signing_context = 3;</code>
   */
  boolean hasSigningContext();
  /**
   * <code>.Catalyst.Protocol.Cryptography.SigningContext signing_context = 3;</code>
   */
  Catalyst.Protocol.Cryptography.SigningContext getSigningContext();
  /**
   * <code>.Catalyst.Protocol.Cryptography.SigningContext signing_context = 3;</code>
   */
  Catalyst.Protocol.Cryptography.SigningContextOrBuilder getSigningContextOrBuilder();
}
