<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Wire.proto

namespace Catalyst\Protocol\Wire;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 **
 * A wrapper around the service message, the contents of service message should be signed by the sender to avoid tampering mid-transit.
 * </pre>
 *
 * Protobuf type <code>Catalyst.Protocol.Wire.ProtocolMessage</code>
 */
class ProtocolMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * is the sender's peerId
     * </pre>
     *
     * <code>.Catalyst.Protocol.Peer.PeerId peer_id = 1;</code>
     */
    private $peer_id = null;
    /**
     * <pre>
     * is a 16 bytes guid used to match responses to their original requests
     * </pre>
     *
     * <code>bytes correlation_id = 2;</code>
     */
    private $correlation_id = '';
    /**
     * <pre>
     * is the shortened protocol name of the message type being encoded in the value field (cf Any from protobuf WellKnownTypes)
     * </pre>
     *
     * <code>string type_url = 3;</code>
     */
    private $type_url = '';
    /**
     * <pre>
     * is the actual value of the message being wrapped (cf Any from protobuf WellKnownTypes)
     * </pre>
     *
     * <code>bytes value = 4;</code>
     */
    private $value = '';
    /**
     * <pre>
     * is the ed25519ph context signature
     * </pre>
     *
     * <code>.Catalyst.Protocol.Cryptography.Signature signature = 5;</code>
     */
    private $signature = null;

    public function __construct() {
        \GPBMetadata\Wire::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * is the sender's peerId
     * </pre>
     *
     * <code>.Catalyst.Protocol.Peer.PeerId peer_id = 1;</code>
     */
    public function getPeerId()
    {
        return $this->peer_id;
    }

    /**
     * <pre>
     * is the sender's peerId
     * </pre>
     *
     * <code>.Catalyst.Protocol.Peer.PeerId peer_id = 1;</code>
     */
    public function setPeerId(&$var)
    {
        GPBUtil::checkMessage($var, \Catalyst\Protocol\Peer\PeerId::class);
        $this->peer_id = $var;
    }

    /**
     * <pre>
     * is a 16 bytes guid used to match responses to their original requests
     * </pre>
     *
     * <code>bytes correlation_id = 2;</code>
     */
    public function getCorrelationId()
    {
        return $this->correlation_id;
    }

    /**
     * <pre>
     * is a 16 bytes guid used to match responses to their original requests
     * </pre>
     *
     * <code>bytes correlation_id = 2;</code>
     */
    public function setCorrelationId($var)
    {
        GPBUtil::checkString($var, False);
        $this->correlation_id = $var;
    }

    /**
     * <pre>
     * is the shortened protocol name of the message type being encoded in the value field (cf Any from protobuf WellKnownTypes)
     * </pre>
     *
     * <code>string type_url = 3;</code>
     */
    public function getTypeUrl()
    {
        return $this->type_url;
    }

    /**
     * <pre>
     * is the shortened protocol name of the message type being encoded in the value field (cf Any from protobuf WellKnownTypes)
     * </pre>
     *
     * <code>string type_url = 3;</code>
     */
    public function setTypeUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->type_url = $var;
    }

    /**
     * <pre>
     * is the actual value of the message being wrapped (cf Any from protobuf WellKnownTypes)
     * </pre>
     *
     * <code>bytes value = 4;</code>
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * <pre>
     * is the actual value of the message being wrapped (cf Any from protobuf WellKnownTypes)
     * </pre>
     *
     * <code>bytes value = 4;</code>
     */
    public function setValue($var)
    {
        GPBUtil::checkString($var, False);
        $this->value = $var;
    }

    /**
     * <pre>
     * is the ed25519ph context signature
     * </pre>
     *
     * <code>.Catalyst.Protocol.Cryptography.Signature signature = 5;</code>
     */
    public function getSignature()
    {
        return $this->signature;
    }

    /**
     * <pre>
     * is the ed25519ph context signature
     * </pre>
     *
     * <code>.Catalyst.Protocol.Cryptography.Signature signature = 5;</code>
     */
    public function setSignature(&$var)
    {
        GPBUtil::checkMessage($var, \Catalyst\Protocol\Cryptography\Signature::class);
        $this->signature = $var;
    }

}

