// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Deltas.proto

package Catalyst.Protocol.Deltas;

public interface DeltaIndexOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Catalyst.Protocol.Deltas.DeltaIndex)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 height = 1;</code>
   */
  int getHeight();

  /**
   * <code>bytes cid = 2;</code>
   */
  com.google.protobuf.ByteString getCid();
}
