trigger:
    - master

pool:
    vmImage: 'ubuntu-latest'

steps:
  - script: |
      echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc

      cd packages/sdk-js && npm install --unsafe-perm --no-optional \
      && npm publish --access public
    displayName: 'Publish NPM package to npmjs.org'
