// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IPPN.proto

package Catalyst.Protocol.IPPN;

/**
 * Protobuf type {@code Catalyst.Protocol.IPPN.LatestDeltaHashResponse}
 */
public  final class LatestDeltaHashResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Catalyst.Protocol.IPPN.LatestDeltaHashResponse)
    LatestDeltaHashResponseOrBuilder {
  // Use LatestDeltaHashResponse.newBuilder() to construct.
  private LatestDeltaHashResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LatestDeltaHashResponse() {
    deltaHash_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private LatestDeltaHashResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {

            deltaHash_ = input.readBytes();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Catalyst.Protocol.IPPN.IPPN.internal_static_Catalyst_Protocol_IPPN_LatestDeltaHashResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Catalyst.Protocol.IPPN.IPPN.internal_static_Catalyst_Protocol_IPPN_LatestDeltaHashResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            Catalyst.Protocol.IPPN.LatestDeltaHashResponse.class, Catalyst.Protocol.IPPN.LatestDeltaHashResponse.Builder.class);
  }

  public static final int DELTA_HASH_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString deltaHash_;
  /**
   * <pre>
   * Rhe cid of a nodes last delta.
   * </pre>
   *
   * <code>bytes delta_hash = 1;</code>
   */
  public com.google.protobuf.ByteString getDeltaHash() {
    return deltaHash_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!deltaHash_.isEmpty()) {
      output.writeBytes(1, deltaHash_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!deltaHash_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, deltaHash_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof Catalyst.Protocol.IPPN.LatestDeltaHashResponse)) {
      return super.equals(obj);
    }
    Catalyst.Protocol.IPPN.LatestDeltaHashResponse other = (Catalyst.Protocol.IPPN.LatestDeltaHashResponse) obj;

    boolean result = true;
    result = result && getDeltaHash()
        .equals(other.getDeltaHash());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DELTA_HASH_FIELD_NUMBER;
    hash = (53 * hash) + getDeltaHash().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static Catalyst.Protocol.IPPN.LatestDeltaHashResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Catalyst.Protocol.IPPN.LatestDeltaHashResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Catalyst.Protocol.IPPN.LatestDeltaHashResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Catalyst.Protocol.IPPN.LatestDeltaHashResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Catalyst.Protocol.IPPN.LatestDeltaHashResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Catalyst.Protocol.IPPN.LatestDeltaHashResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static Catalyst.Protocol.IPPN.LatestDeltaHashResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static Catalyst.Protocol.IPPN.LatestDeltaHashResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static Catalyst.Protocol.IPPN.LatestDeltaHashResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Catalyst.Protocol.IPPN.LatestDeltaHashResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(Catalyst.Protocol.IPPN.LatestDeltaHashResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Catalyst.Protocol.IPPN.LatestDeltaHashResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Catalyst.Protocol.IPPN.LatestDeltaHashResponse)
      Catalyst.Protocol.IPPN.LatestDeltaHashResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Catalyst.Protocol.IPPN.IPPN.internal_static_Catalyst_Protocol_IPPN_LatestDeltaHashResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Catalyst.Protocol.IPPN.IPPN.internal_static_Catalyst_Protocol_IPPN_LatestDeltaHashResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Catalyst.Protocol.IPPN.LatestDeltaHashResponse.class, Catalyst.Protocol.IPPN.LatestDeltaHashResponse.Builder.class);
    }

    // Construct using Catalyst.Protocol.IPPN.LatestDeltaHashResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      deltaHash_ = com.google.protobuf.ByteString.EMPTY;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Catalyst.Protocol.IPPN.IPPN.internal_static_Catalyst_Protocol_IPPN_LatestDeltaHashResponse_descriptor;
    }

    public Catalyst.Protocol.IPPN.LatestDeltaHashResponse getDefaultInstanceForType() {
      return Catalyst.Protocol.IPPN.LatestDeltaHashResponse.getDefaultInstance();
    }

    public Catalyst.Protocol.IPPN.LatestDeltaHashResponse build() {
      Catalyst.Protocol.IPPN.LatestDeltaHashResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public Catalyst.Protocol.IPPN.LatestDeltaHashResponse buildPartial() {
      Catalyst.Protocol.IPPN.LatestDeltaHashResponse result = new Catalyst.Protocol.IPPN.LatestDeltaHashResponse(this);
      result.deltaHash_ = deltaHash_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof Catalyst.Protocol.IPPN.LatestDeltaHashResponse) {
        return mergeFrom((Catalyst.Protocol.IPPN.LatestDeltaHashResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(Catalyst.Protocol.IPPN.LatestDeltaHashResponse other) {
      if (other == Catalyst.Protocol.IPPN.LatestDeltaHashResponse.getDefaultInstance()) return this;
      if (other.getDeltaHash() != com.google.protobuf.ByteString.EMPTY) {
        setDeltaHash(other.getDeltaHash());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Catalyst.Protocol.IPPN.LatestDeltaHashResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (Catalyst.Protocol.IPPN.LatestDeltaHashResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.google.protobuf.ByteString deltaHash_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * Rhe cid of a nodes last delta.
     * </pre>
     *
     * <code>bytes delta_hash = 1;</code>
     */
    public com.google.protobuf.ByteString getDeltaHash() {
      return deltaHash_;
    }
    /**
     * <pre>
     * Rhe cid of a nodes last delta.
     * </pre>
     *
     * <code>bytes delta_hash = 1;</code>
     */
    public Builder setDeltaHash(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      deltaHash_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Rhe cid of a nodes last delta.
     * </pre>
     *
     * <code>bytes delta_hash = 1;</code>
     */
    public Builder clearDeltaHash() {
      
      deltaHash_ = getDefaultInstance().getDeltaHash();
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:Catalyst.Protocol.IPPN.LatestDeltaHashResponse)
  }

  // @@protoc_insertion_point(class_scope:Catalyst.Protocol.IPPN.LatestDeltaHashResponse)
  private static final Catalyst.Protocol.IPPN.LatestDeltaHashResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Catalyst.Protocol.IPPN.LatestDeltaHashResponse();
  }

  public static Catalyst.Protocol.IPPN.LatestDeltaHashResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LatestDeltaHashResponse>
      PARSER = new com.google.protobuf.AbstractParser<LatestDeltaHashResponse>() {
    public LatestDeltaHashResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new LatestDeltaHashResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<LatestDeltaHashResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LatestDeltaHashResponse> getParserForType() {
    return PARSER;
  }

  public Catalyst.Protocol.IPPN.LatestDeltaHashResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

