// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IPPN.proto

package Catalyst.Protocol.IPPN;

public interface PingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Catalyst.Protocol.IPPN.PingResponse)
    com.google.protobuf.MessageOrBuilder {
}
