<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Peer.proto

namespace GPBMetadata;

class Peer
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\Timestamp::initOnce();
        \GPBMetadata\Google\Protobuf\Duration::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ae6030a0a506565722e70726f746f1216436174616c7973742e50726f74" .
            "6f636f6c2e506565721a1f676f6f676c652f70726f746f6275662f74696d" .
            "657374616d702e70726f746f1a1e676f6f676c652f70726f746f6275662f" .
            "6475726174696f6e2e70726f746f22360a06506565724964120a0a026970" .
            "18012001280c120c0a04706f727418022001280d12120a0a7075626c6963" .
            "5f6b657918032001280c22ba020a0850656572496e666f122f0a07706565" .
            "725f696418012001280b321e2e436174616c7973742e50726f746f636f6c" .
            "2e506565722e50656572496412120a0a72657075746174696f6e18022001" .
            "281112160a0e69735f626c61636b6c697374656418032001280812160a0e" .
            "69735f756e726561636861626c65180420012808122f0a0c696e61637469" .
            "76655f666f7218052001280b32192e676f6f676c652e70726f746f627566" .
            "2e4475726174696f6e122d0a096c6173745f7365656e18062001280b321a" .
            "2e676f6f676c652e70726f746f6275662e54696d657374616d70122c0a08" .
            "6d6f64696669656418072001280b321a2e676f6f676c652e70726f746f62" .
            "75662e54696d657374616d70122b0a076372656174656418082001280b32" .
            "1a2e676f6f676c652e70726f746f6275662e54696d657374616d70420250" .
            "01620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

