<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: IPPN.proto

namespace Catalyst\Protocol\IPPN;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>Catalyst.Protocol.IPPN.LatestDeltaHashResponse</code>
 */
class LatestDeltaHashResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * Rhe cid of a nodes last delta.
     * </pre>
     *
     * <code>bytes delta_hash = 1;</code>
     */
    private $delta_hash = '';

    public function __construct() {
        \GPBMetadata\IPPN::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * Rhe cid of a nodes last delta.
     * </pre>
     *
     * <code>bytes delta_hash = 1;</code>
     */
    public function getDeltaHash()
    {
        return $this->delta_hash;
    }

    /**
     * <pre>
     * Rhe cid of a nodes last delta.
     * </pre>
     *
     * <code>bytes delta_hash = 1;</code>
     */
    public function setDeltaHash($var)
    {
        GPBUtil::checkString($var, False);
        $this->delta_hash = $var;
    }

}

