// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Wire.proto

package Catalyst.Protocol.Wire;

public interface CandidateDeltaBroadcastOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Catalyst.Protocol.Wire.CandidateDeltaBroadcast)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The hash computed for the current delta produced by ProducerId. This is meant to be used when voting for most popular hashes.
   * </pre>
   *
   * <code>bytes hash = 1;</code>
   * @return The hash.
   */
  com.google.protobuf.ByteString getHash();

  /**
   * <pre>
   * Identifier of the producer of the candidate.
   * </pre>
   *
   * <code>.Catalyst.Protocol.Peer.PeerId producer_id = 2;</code>
   * @return Whether the producerId field is set.
   */
  boolean hasProducerId();
  /**
   * <pre>
   * Identifier of the producer of the candidate.
   * </pre>
   *
   * <code>.Catalyst.Protocol.Peer.PeerId producer_id = 2;</code>
   * @return The producerId.
   */
  Catalyst.Protocol.Peer.PeerId getProducerId();
  /**
   * <pre>
   * Identifier of the producer of the candidate.
   * </pre>
   *
   * <code>.Catalyst.Protocol.Peer.PeerId producer_id = 2;</code>
   */
  Catalyst.Protocol.Peer.PeerIdOrBuilder getProducerIdOrBuilder();

  /**
   * <pre>
   * The DFS address for the content of the delta preceding this candidate.
   * </pre>
   *
   * <code>bytes previous_delta_dfs_hash = 3;</code>
   * @return The previousDeltaDfsHash.
   */
  com.google.protobuf.ByteString getPreviousDeltaDfsHash();
}
